### ISSUE TITLE
Incorrect encoding from SSEClient

### ISSUE THREAD

**Issue by busla** [thisbejim/Pyrebase#103]
The SSEClient seems to be returning incorrect char encoding. 

I get the correct encoding on .get().val() during my initial request but the stream is returning something totally different.

This: `'Ã\x86vintÃ½ri Berta og Ã\x81rna'`
Should be like this: `Ævintýri Berta og Árna`

**Comment by thisbejim** [comment]
Hi @busla, this has been [brought up before](https://github.com/thisbejim/Pyrebase/issues/81) and unfortunately I do not know the solution. I recommend forking Pyrebase and playing around with encoding in SSEClient to see if you can get the results you are after or generally try to avoid using special characters.

**Comment by busla** [comment]
Ok, thanks.

Instead of installing a package for this I´ll encode it on my end to *latin-1* and then decode back to *UTF-8*:

`my_string.encode('latin1').decode('utf-8')`

**Comment by busla** [comment]
Referencing #81

**Comment by thisbejim** [comment]
Awesome, thanks for replying with the solution @busla!

**Comment by busla** [comment]
Oops, Icelandic characters missing from latin-1.

Let´s use:
`my_string.encode('iso-8859-1').decode('iso-8859-1')`

**Comment by busla** [comment]
The problem was not fixed.

This only fixes a few characters so I guess we need to ask the Firebase team to return a charset=UTF-8 with the *text/event-stream*

I´ve sent a support request to them so let´s see what happens.

**Comment by busla** [comment]
Just to follow up on this, Google is still working on the issue. They´ve sent me an email every two days about their progress.

**Comment by thisbejim** [comment]
Awesome stuff! Thanks for the update.

**Comment by shamrin** [comment]
Here's the function I currently use to work around broken strings:

```python
def fix_encoding(s):
    """Fix bad encoding with an ugly hack

    https://github.com/thisbejim/Pyrebase/issues/103
    https://github.com/thisbejim/Pyrebase/issues/81
    """
    try:
        # fix broken string
        return s.encode('latin-1').decode('utf8')
    except UnicodeError:
        # this is for the time when Google or Pyrebase would fix the bug
        return ftfy.fix_encoding(s)
```

**Comment by shamrin** [comment]
Another possibility is this, but I haven't tested it:

```python
def fix_encoding(s):
    """Fix bad encoding with an ugly hack

    https://github.com/thisbejim/Pyrebase/issues/103
    https://github.com/thisbejim/Pyrebase/issues/81
    """
    try:
        return s.encode('latin-1').decode('utf8')
    except UnicodeError:
        # this is for the time when Google or Pyrebase would fix the bug
        return s
```

**Comment by rockwotj** [comment]
Engineer for the Realtime Database here. We aren't setting the charset in the event-stream header. I've submitted a patch for this and it should be fixed late next week

**Comment by busla** [comment]
This seems to be fixed. I am getting correct encoding now.

@rockwotj thanks for putting effort into resolving this :-) I appreciate it.

**Comment by shamrin** [comment]
By the way, I'm still getting incorrect encoding and had to do `s.encode('latin-1').decode('utf8')` to cure the broken string. I think I'll wait for "late next week" (@rockwotj) before removing the cure.

**Comment by rockwotj** [comment]
Please try it out now, and let me know if it doesn't work.

**Comment by shamrin** [comment]
@rockwotj It works great now, thank you very much!

Good bye, ugly hacks!
