### ISSUE TITLE
Fails install on googleapis-common-protos

### ISSUE THREAD

**Issue by MichaelHipp** [thisbejim/Pyrebase#236]
I'm getting an install failure on googleapis-common-protos. I don't see any obvious way to submit an issue on that package as it's not really a python package per se. Any suggestions?

```
Running setup.py install for googleapis-common-protos: started
    Running setup.py install for googleapis-common-protos: finished with status 'error'
    Complete output from command c:\users\michael\virtenvs\oldworldblack\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\slash\\tmp\\pip-build-c31cttjl\\googleapis-common-protos\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\slash\tmp\pip-viyk6w3a-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\michael\virtenvs\oldworldblack\include\site\python3.6\googleapis-common-protos:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\michael\virtenvs\oldworldblack\lib\site-packages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "c:\users\michael\virtenvs\oldworldblack\lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "c:\users\michael\virtenvs\oldworldblack\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
        @_call_aside
      File "c:\users\michael\virtenvs\oldworldblack\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "c:\users\michael\virtenvs\oldworldblack\lib\site-packages\pkg_resources\__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "c:\users\michael\virtenvs\oldworldblack\lib\site-packages\pkg_resources\__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "c:\users\michael\virtenvs\oldworldblack\lib\site-packages\pkg_resources\__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\michael\virtenvs\oldworldblack\lib\site-packages\pkg_resources\__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "c:\users\michael\virtenvs\oldworldblack\lib\site-packages\pkg_resources\__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "c:\users\michael\virtenvs\oldworldblack\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\slash\\tmp\\pip-build-c31cttjl\\googleapis-common-protos\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\slash\tmp\pip-viyk6w3a-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\michael\virtenvs\oldworldblack\include\site\python3.6\googleapis-common-protos" failed with error code 1 in C:\slash\tmp\pip-build-c31cttjl\googleapis-common-protos\

````

**Comment by gleidiin** [comment]
Hi @MichaelHipp check the issue #179 error, I fixed the same problem with it. :)

**Comment by MichaelHipp** [comment]
No joy here. I'm still getting the same error after running `pip install --upgrade setuptools`.

```
 ➤ pip list
pip (9.0.1)
setuptools (38.4.0)
virtualenv (15.1.0)
```

**Comment by Drachenfels** [comment]
I am running:

 - ubuntu 16.04
 - virtualenv 15.0.1

I do following:

mkvirtualenv yolo -p $(which python3)

Then if I do:

pip install --no-cache-dir googleapis-common-protos

I have exception with NamespacePath

But if I do:

pip install googleapis-common-protos

It works.

**Comment by Drachenfels** [comment]
ups, sorry guys I thought I am typing on googleapis issues board. Please ignore. :-D

**Comment by Maunty** [comment]
pip install --upgrade pip

usually the problem is too old pip version.

**Comment by lvZic** [comment]
it still exists!!!

ERROR: Command errored out with exit status 1:
     command: /home/lvzhen/py351/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jyfhb9ai/googleapis-common-protos/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jyfhb9ai/googleapis-common-protos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ms1ly0se
         cwd: /tmp/pip-install-jyfhb9ai/googleapis-common-protos/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lvzhen/py351/lib/python3.5/site-packages/setuptools/__init__.py", line 17, in <module>
        import setuptools.version
      File "/home/lvzhen/py351/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/lvzhen/py351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/home/lvzhen/py351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/home/lvzhen/py351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/lvzhen/py351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/home/lvzhen/py351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/lvzhen/py351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/home/lvzhen/py351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/lvzhen/py351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/lvzhen/py351/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    ----------------------------------------

**Comment by lvZic** [comment]
> No joy here. I'm still getting the same error after running `pip install --upgrade setuptools`.
> 
> ```
>  ➤ pip list
> pip (9.0.1)
> setuptools (38.4.0)
> virtualenv (15.1.0)
> ```

have u fixed it?

**Comment by venkz** [comment]
@lz2004xxw If you are still having issues with this just try updating your setup tools

`pip install --upgrade setuptools`

**Comment by lvZic** [comment]
> @lz2004xxw If you are still having issues with this just try updating your setup tools
> 
> `pip install --upgrade setuptools`

i forgot the solution， it seems it have been solved before.
