### ISSUE TITLE
AttributeError: module 'pyrebase' has no attribute 'initialize_app'

### ISSUE THREAD

**Issue by river-fall** [thisbejim/Pyrebase#66]
Hi,

I have this issue:

```
bash-3.2$ ./pyrebase.py
Traceback (most recent call last):
  File "./pyrebase.py", line 3, in <module>
    import pyrebase
  File "/Users/arsenyosipov/Documents/COBI/python-search/pyrebase.py", line 13, in <module>
    fire = pyrebase.initialize_app(config)
AttributeError: module 'pyrebase' has no attribute 'initialize_app'

bash-3.2$ python3 --version
Python 3.5.2
```

The script:
```
#!/usr/local/bin/python3

import pyrebase

config = {
  "apiKey": "key",
  "authDomain": "project.firebaseapp.com",
  "databaseURL": "https://project.firebaseio.com",
  "storageBucket": "project.appspot.com",
  "serviceAccount": "python.json"
}

fire = pyrebase.initialize_app(config)
```

**Comment by lsenta** [comment]
Rename your script, it's hiding the library.

**Comment by soumilshah1995** [comment]
i am getting same issue 

Traceback (most recent call last):
  File "/Users/soumilshah/IdeaProjects/Mongo/aaa.py", line 1, in <module>
    import pyrebase
  File "/Users/soumilshah/IdeaProjects/Mongo/pyrebase.py", line 12, in <module>
    firebase = pyrebase.initialize_app(config)
AttributeError: module 'pyrebase' has no attribute 'initialize_app'

**Comment by lsenta** [comment]
Hey @soumilshah1995 a few ideas to get started:

- Could you share how you start the script?
- Could you share the content of your script?
- Could you try a `python --version` and let us know what you get?

**Comment by stephennacion06** [comment]
I have the same issue but i fixed it by making sure there is no pyrebase.py filename inside the folder where my python script is located

**Comment by DeepakGitHub050** [comment]
because the pyrebase module is not able to fetch the file. to solve this you have to save your file in that location where the pyrebase module is installed.

**Comment by rajatsingharia215** [comment]
I am also facing the same issue and I have installed it and uninstalled everything and re-installed it and still get the same Attribute-Error

**Comment by DeepakGitHub050** [comment]
> I am also facing the same issue and I have installed it and uninstalled everything and re-installed it and still get the same Attribute-Error

save your project file in the same folder which has pyrebase package installed

**Comment by AzharUddinSheikh** [comment]
I am stuck please help me 

i have installed pip install pyrebase4 

then i got attribute error 

So I try pip list 
(I see no such pyrebase4 in a list of installed packages)
I try pip3 list
(yes pyrebase4 available) 

what I do
